version: '3.9'

volumes:
  pg_data:
  frontend_data:
  media:

services:

  db:
    container_name: foodgram_database
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: mxstrv/foodgram_backend
    env_file: ../.env
    volumes:
      - media:/app/media/
      - frontend_data:/app/static/
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    image: mxstrv/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    container_name: foodgram_gateway
    image: nginx:1.22.1
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - frontend_data:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend
